#!/bin/bash

#SBATCH -A "MINT" #account numberID
#SBATCH -t 7-0:00:00 #time
#SBATCH -N "1" #nodes 64 cores


module load java/1.7.0_10 
module load python/anaconda2 
python das_pipeline_v002.py -input_dir "/pic/projects/mint2/Chowdhury_cDNA-29727713/input" -output_dir "/pic/projects/mint2/Chowdhury_cDNA-29727713/output" -config_file "/pic/projects/mint2/Chowdhury_cDNA-29727713/das_config.txt" -param_file "/pic/projects/mint2/Chowdhury_cDNA-29727713/das_param.txt" 
