## use just in time compilation for bbmap
usejni: false

gene_annotations:
  - dram

genome_filter_criteria: "(Completeness-5*Contamination >50 ) & (Length_scaffolds >=50000) & (Ambigious_bases <1e6) & (N50 > 5*1e3) & (N_scaffolds < 1e3)"
exclude_unplacable_genomes: false

genome_dereplication:
  ANI: 0.95                        ## Genome dreplication threshold
  overlap: 0.2                  # See more on https://drep.readthedocs.io/en/latest/module_descriptions.html
  greedy_clustering: "auto"     # Add options for greedy clustering 'auto' when using more than 5k bins
  opt_parameters: ""
  score:
    completeness: 1
    contamination: 5
    N50: 0.5
    length: 0
    centrality: 1

genome_aligner: "minimap"

bin_quality_asesser: checkm2          #[ checkm2, busco, cehckm]
gunc_database: "progenomes"  # progenomes or gtdb

semibin_train_extra: ""